### PR TITLE
Create outline.md

### PR DESCRIPTION
**Pull request by rrrutledge**
Excited for review from @mrsanz, @utanapishtim, and anyone else who's interested

### CODE REVIEW

**Review by utanapishtim — APPROVED** [review]
LGTM

**Comment by utanapishtim** [comment]
This looks like the talk I've seen you give in the past.

**Review by mrsanz — APPROVED** [review]
LGTM

**Comment by rrrutledge** [comment]
> This looks like the talk I've seen you give in the past.

It's a combination of the O'Reilly-hosted learning path and the ISC 2018 Spring Summit

**Pull request merged**
